// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-about.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { personalInfo } from "npm:@/data/personal-info";
var get_about_default = defineTool({
  name: "get_about",
  title: "Get about Nithin Varma",
  description: "Returns Nithin Varma's public profile: basics, education, interests, achievements, and goals as shown on the portfolio.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(personalInfo, null, 2) }],
    structuredContent: personalInfo
  })
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { personalInfo as personalInfo2 } from "npm:@/data/personal-info";
var projects = [
  { title: "Brain Candy", category: "Education", description: "An innovative education platform designed to enhance learning experiences." },
  { title: "BrainCandy AI Study Assistant", category: "AI & Education", description: "An AI-powered study assistant that helps students with learning and productivity." },
  { title: "Matrix-Based Computer", category: "Computing", description: "A next-generation computing system utilizing a multidimensional matrix structure." },
  { title: "Cloudix", category: "Gaming", description: "A cloud gaming service offering optimized connectivity and performance." },
  { title: "Green Terra", category: "Sustainability", description: "A plant-based food service with eco-friendly packaging and a sustainable approach." },
  { title: "Feastify", category: "Food Tech", description: "A cloud restaurant concept providing high-quality meals through online delivery." },
  { title: "Waveroo", category: "Audio", description: "A music and audio platform concept." },
  { title: "Minimate", category: "Product", description: "A minimalist product concept." },
  { title: "Radianto", category: "Space", description: "A space station concept." },
  { title: "Velox", category: "Mobility", description: "A next-gen mobility concept." },
  { title: "Evolvion", category: "Innovation", description: "An evolution-focused innovation concept." },
  { title: "Gravix", category: "Tech", description: "A gravity/physics-related tech concept." },
  { title: "Lumin", category: "Lifestyle", description: "A lighting/lifestyle concept." },
  { title: "QuickFix", category: "Personal Project", description: "A personal project built for fun." },
  { title: "STANDARD", category: "Personal Project", description: "A minimal wallpaper library." },
  { title: "SpankUrLaptop", category: "Personal Project", description: "The Windows answer to a viral Mac-only trend \u2014 a Python-based audio processing app." },
  { title: "FitForge AI", category: "AI", description: "An AI-integrated fitness project." },
  { title: "Orbis Launchpad", category: "Personal Project", description: "A UI flex frontend project showcasing modern design and interactive layouts." }
];
var list_projects_default = defineTool2({
  name: "list_projects",
  title: "List projects",
  description: "Lists all projects featured on Nithin Varma's portfolio with their category and short description.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: `${projects.length} projects on the portfolio (source list of names also available on the profile): ${personalInfo2.projects.join(", ")}

${JSON.stringify(projects, null, 2)}`
      }
    ],
    structuredContent: { projects }
  })
});

// src/lib/mcp/tools/list-skills.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var skills = {
  technical: [
    "Python",
    "Data Analytics",
    "AI/ML Concepts",
    "Generative AI (Gen AI)",
    "Cloud Technologies",
    "Business Technology",
    "Advanced Excel",
    "Project Management"
  ],
  business: [
    "Entrepreneurial Thinking",
    "Business Model Ideation",
    "Market Analysis",
    "Pitch Creation",
    "Product Management",
    "Sustainability Concepts",
    "Product Conceptualization"
  ],
  soft: [
    "Strategic Thinking",
    "Creative Ideation",
    "Improving Communication Skills",
    "Adaptability",
    "Problem Solving"
  ]
};
var list_skills_default = defineTool3({
  name: "list_skills",
  title: "List skills",
  description: "Lists Nithin Varma's skills grouped by technical, business, and soft skill categories.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(skills, null, 2) }],
    structuredContent: skills
  })
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { personalInfo as personalInfo3 } from "npm:@/data/personal-info";
var get_contact_default = defineTool4({
  name: "get_contact",
  title: "Get contact info",
  description: "Returns Nithin Varma's public contact information (email, phone, location) as listed on the portfolio.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: `Email: ${personalInfo3.basics.email}
Phone: ${personalInfo3.basics.phone}
Location: ${personalInfo3.basics.location}`
      }
    ],
    structuredContent: {
      email: personalInfo3.basics.email,
      phone: personalInfo3.basics.phone,
      location: personalInfo3.basics.location
    }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "nithin-varma-portfolio",
  title: "Nithin Varma Portfolio",
  version: "0.1.0",
  instructions: "Public MCP server for Nithin Varma's portfolio. Use these tools to look up his profile, projects, skills, and contact info.",
  tools: [get_about_default, list_projects_default, list_skills_default, get_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
